import React, {useEffect, useState} from 'react';
import {BarChart3, FileSpreadsheet, Gauge, Search, TrendingUp, X, Check} from 'lucide-react';
const API='http://localhost:8787';
export const GoogleIntegrationPanel:React.FC<{onClose:()=>void}>=({onClose})=>{
 const [connected,setConnected]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{fetch(`${API}/api/google/status`).then(r=>r.json()).then(d=>setConnected(!!d.connected)).catch(()=>setError('Start the tools server first.'));},[]);
 const connect=()=>{window.location.href=`${API}/api/google/start`};
 const disconnect=async()=>{await fetch(`${API}/api/google/disconnect`,{method:'POST'});setConnected(false)};
 const cards=[['Search Console',Search,'Queries, clicks, impressions, CTR and average position.'],['Analytics 4',BarChart3,'Users, sessions, page views and conversions.'],['PageSpeed',Gauge,'Performance, accessibility, SEO and Core Web Vitals.'],['Google Trends',TrendingUp,'Rising search topics and public trending queries by market.'],['Google Sheets',FileSpreadsheet,'Write executive SEO and growth reports into spreadsheets.']];
 return <div className="fixed inset-0 z-[110] bg-black/40 backdrop-blur-sm flex items-center justify-center p-4"><div className="w-full max-w-5xl max-h-[90vh] overflow-auto bg-white rounded-3xl shadow-2xl"><div className="p-6 border-b flex justify-between items-center"><div><div className="text-[10px] font-black uppercase tracking-[.2em] text-blue-600">Google Workspace</div><h2 className="text-2xl font-black mt-1">Growth Intelligence</h2><p className="text-sm text-zinc-500 mt-1">Connect Google once. Give selected agents read access to growth data and controlled reporting.</p></div><button onClick={onClose} className="p-2 border rounded-xl"><X size={18}/></button></div><div className="p-6"><div className="flex items-center justify-between p-5 rounded-2xl border bg-zinc-50"><div><div className="flex items-center gap-2"><span className={`w-2.5 h-2.5 rounded-full ${connected?'bg-emerald-500':'bg-zinc-300'}`}/><b className="text-sm">{connected?'Google connected':'Google not connected'}</b></div><p className="text-xs text-zinc-500 mt-2">OAuth tokens are stored encrypted by the local tools server.</p></div>{connected?<button onClick={disconnect} className="px-4 py-2 rounded-xl border bg-white text-xs font-bold">Disconnect</button>:<button onClick={connect} className="px-4 py-2 rounded-xl bg-black text-white text-xs font-bold">Sign in with Google</button>}</div>{error&&<div className="mt-4 p-3 rounded-xl bg-amber-50 text-amber-800 text-xs">{error}</div>}<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mt-6">{cards.map(([name,Icon,desc])=><div key={name as string} className="p-5 rounded-2xl border bg-white"><Icon size={20}/><h3 className="font-bold text-sm mt-3">{name as string}</h3><p className="text-xs text-zinc-500 mt-2">{desc as string}</p><span className="inline-flex items-center gap-1 text-[10px] font-bold text-emerald-600 mt-4"><Check size={12}/> Agent Tool Available</span></div>)}</div><div className="mt-6 p-5 rounded-2xl border bg-blue-50"><b className="text-sm">Recommended Eldevo workflow</b><p className="text-xs text-zinc-600 mt-2">Trends → Search Console → GA4 → PageSpeed → Developer → QA → Google Sheets report. Production changes remain behind Human Approval.</p></div></div></div></div>;
};
